# Testing http requests with Visual Studio Code REST Client extension

###########################
## Users resource endpoints

### get all users
GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJ1c2VybmFtZSI6IngzNDUiLCJwYXNzd29yZCI6IiQyYSQxMCRYVnUyQTJyT0N3Nm9CUm14bEpSSGIuUi9MMWlMV2o2TS9EZ2RSczZqdTBwWnB6ajhmNzFpZSIsImVtYWlsIjoieHhAZXhhbXBsZS5jb20iLCJjcmVhdGVkX2F0IjoiMjAyNS0wMy0wM1QxNToxNjo0OS4wMDBaIiwidXNlcl9sZXZlbCI6InJlZ3VsYXIiLCJpYXQiOjE3NDE2MzczNTEsImV4cCI6MTc0MTcyMzc1MX0.thC7u2NOLUBx3SGYTFM0Vpay44uaEBdDiSfV-hH2Y10

### get user by id
GET http://localhost:3000/api/users/3

### create a new user (user registration)
POST http://localhost:3000/api/users
content-type: application/json

{
  "username": "x345",
  "password": "x1234567",
  "email": "xx@example.com"
}

### modify an existing user by id
PUT http://localhost:3000/api/users/3
content-type: application/json

{
  "username": "editedname",
  "password": "editedpasswordx",
  "email": "editedmail@example.com"
}

### delete a user (by id)
DELETE http://localhost:3000/api/users/3

### user login
POST http://localhost:3000/api/auth/login
content-type: application/json

{
  "username": "x345",
  "password": "x1234567"
}

### get my user info
GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJ1c2VybmFtZSI6IngzNDUiLCJwYXNzd29yZCI6IiQyYSQxMCRYVnUyQTJyT0N3Nm9CUm14bEpSSGIuUi9MMWlMV2o2TS9EZ2RSczZqdTBwWnB6ajhmNzFpZSIsImVtYWlsIjoieHhAZXhhbXBsZS5jb20iLCJjcmVhdGVkX2F0IjoiMjAyNS0wMy0wM1QxNToxNjo0OS4wMDBaIiwidXNlcl9sZXZlbCI6InJlZ3VsYXIiLCJpYXQiOjE3NDE2MzczNTEsImV4cCI6MTc0MTcyMzc1MX0.thC7u2NOLUBx3SGYTFM0Vpay44uaEBdDiSfV-hH2Y10
## (Diary)Entries

### post a new entry
POST http://localhost:3000/api/entries
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJ1c2VybmFtZSI6IngzNDUiLCJwYXNzd29yZCI6IiQyYSQxMCRYVnUyQTJyT0N3Nm9CUm14bEpSSGIuUi9MMWlMV2o2TS9EZ2RSczZqdTBwWnB6ajhmNzFpZSIsImVtYWlsIjoieHhAZXhhbXBsZS5jb20iLCJjcmVhdGVkX2F0IjoiMjAyNS0wMy0wM1QxNToxNjo0OS4wMDBaIiwidXNlcl9sZXZlbCI6InJlZ3VsYXIiLCJpYXQiOjE3NDE2MzczNTEsImV4cCI6MTc0MTcyMzc1MX0.thC7u2NOLUBx3SGYTFM0Vpay44uaEBdDiSfV-hH2Y10
content-type: application/json

{
 "entry_date": "2025-02-27",
 "mood": "iloinen",
 "weight": 60,
 "sleep_hours": 6,
 "notes": "Tänään oli huono päivä"
}

### Get user's entries
GET http://localhost:3000/api/entries
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo3LCJ1c2VybmFtZSI6IngzNDUiLCJwYXNzd29yZCI6IiQyYSQxMCRYVnUyQTJyT0N3Nm9CUm14bEpSSGIuUi9MMWlMV2o2TS9EZ2RSczZqdTBwWnB6ajhmNzFpZSIsImVtYWlsIjoieHhAZXhhbXBsZS5jb20iLCJjcmVhdGVkX2F0IjoiMjAyNS0wMy0wM1QxNToxNjo0OS4wMDBaIiwidXNlcl9sZXZlbCI6InJlZ3VsYXIiLCJpYXQiOjE3NDE2MzczNTEsImV4cCI6MTc0MTcyMzc1MX0.thC7u2NOLUBx3SGYTFM0Vpay44uaEBdDiSfV-hH2Y10
