# ekat testit

### Palvelimen juuri
GET http://localhost:3000

### morotesti
GET http://localhost:3000/moro

### morotesti POST
POST http://localhost:3000/api/moro
content-type: application/json

{
  "sender": "kalle",
  "message": "testitervehdys"
}
